spring.application.name=spring-boot-practice
management.endpoints.web.exposure.include=health,info,metrics,beans,loggers,threaddump
management.endpoint.health.show-details=always
management.endpoints.web.exposure.exclude=env
chat.max-message-length=1000
chat.max-room-name-length=50
chat.inactive-user-threshold=30
chat.max-users-per-room=100
chat.message-history-limit=100