spring.application.name=spring-boot-practice
management.endpoints.web.exposure.include=health,info,metrics,beans,loggers,threaddump
management.endpoint.health.show-details=always
management.endpoints.web.exposure.exclude=env