spring:
  application:
    name: spring-boot-practice
  jackson:
    default-property-inclusion:
      non-null: true
  mail:
   host: smtp.gmail.com
   port: 587
   properties:
     mail.smtp.auth: true
     mail.smtp.starttls.enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,loggers,threaddump
        exclude: env
  endpoint:
    health:
      show-details: always