spring.application.name=spring-boot-practice
management.endpoints.web.exposure.include=health,info,metrics,beans,loggers,threaddump
management.endpoint.health.show-details=always
car.name=Toyota
management.endpoints.web.exposure.exclude=env
#can see the active profile in env variable without init it here! spring.profiles.active=dev or spring.application.active=dev
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.cache.type=redis
spring.cache.redis.host=localhost
spring.cache.redis.port=6379
file.upload-dir=uploads